name: "Giessdenkiez.de DWD Harvester"
description: "Collect rain data from the DWD for the giessdenkiez.de app"
inputs:
  PG_SERVER:
    description: "The server where the PostgreSQL database lives"
    required: true
  PG_PORT:
    required: true
    description: "The port of the PostgreSQL database"
    default: 5432
  PG_USER:
    required: true
    description: "The user of the PostgreSQL database"
  PG_PASS:
    required: true
    description: "The password of the PostgreSQL database"
  PG_DB:
    required: true
    description: "The name of the PostgreSQL database"
  SUPABASE_URL:
    required: true
    description: "The base URL to Supabase, e.g. http://localhost:54321 for a local Supabase"
  SUPABASE_SERVICE_ROLE_KEY:
    required: true
    description: "The service role key for accessing the Supabase bucket"
  SUPABASE_BUCKET_NAME:
    description: "The bucket name where the harvested data should be pushed to"
    required: true
  OUTPUT:
    description: ""
    required: true
    default: "True"
  MAPBOXUSERNAME:
    description: "The Mapbox account to which the tileset is sent"
    required: true
  MAPBOXTOKEN:
    description: "The associated token of the Mapbox account"
    required: true
  MAPBOXTILESET:
    description: "The name the tileset should receive"
    required: true
  MAPBOXLAYERNAME:
    description: "The layer within the tileset that holds the trees data"
    required: true
  LOGGING:
    description: ""
    required: true
    default: "INFO"
runs:
  using: "docker"
  image: "harvester/Dockerfile"
  env:
    PG_SERVER: ${{ inputs.PG_SERVER }}
    PG_PORT: ${{ inputs.PG_PORT }}
    PG_USER: ${{ inputs.PG_USER }}
    PG_PASS: ${{ inputs.PG_PASS }}
    PG_DB: ${{ inputs.PG_DB }}
    SUPABASE_URL: ${{ inputs.SUPABASE_URL }}
    SUPABASE_SERVICE_ROLE_KEY: ${{ inputs.SUPABASE_SERVICE_ROLE_KEY }}
    SUPABASE_BUCKET_NAME: ${{ inputs.SUPABASE_BUCKET_NAME }}
    MAPBOXUSERNAME: ${{ inputs.MAPBOXUSERNAME }}
    MAPBOXTOKEN: ${{ inputs.MAPBOXTOKEN }}
    MAPBOXTILESET: ${{ inputs.MAPBOXTILESET }}
    MAPBOXLAYERNAME: ${{ inputs.MAPBOXLAYERNAME }}
    LOGGING: ${{ inputs.LOGGING }}
    DATABASE_URL: ${{ inputs.DATABASE_URL }}
