name: Docker Image Builder

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  HARVESTER_FOLDER: harvester/
  SURROUNDING_SHAPE_FILE: "/app/assets/berlin.shp"

on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Get the source
        uses: actions/checkout@v3
      - name: Docker login, build and push
        run: |
          cd $HARVESTER_FOLDER
          echo "$DOCKER_PASSWORD" |  docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build \
          --label version=${GITHUB_REF##*/} \
          --build-arg SURROUNDING_SHAPE_FILE='${{ env.SURROUNDING_SHAPE_FILE }}' \
          --tag "${GITHUB_REPOSITORY}:${GITHUB_REF##*/}" .
          docker push "${GITHUB_REPOSITORY}:${GITHUB_REF##*/}"
